# Generated by Django 3.1.6 on 2021-02-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mae', to='pages.parent')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='pages.parent')),
            ],
        ),
    ]
